// frontend/src/lib/Menu.svelte
<script lang="ts">
  import { beforeNavigate } from '$app/navigation'

  import type { FaceIndex, HexagonSide } from '$lib/material/svg/types'
  import Svg from '$lib/material/svg/Svg.svelte'
  import Hexagon from '$lib/material/svg/Hexagon.svelte'
  import MenuLines from '$lib/material/svg/MenuLines.svelte'
  import ClickOutside from '$lib/material/ClickOutside.svelte'

  type MenuItem = { label: string; href: string; external?: boolean }

  export let items: MenuItem[] = []
  export let size = 50
  let open = false

  beforeNavigate(() => {
    open = false
  })

  function drawPatern(
    patern: FaceIndex[],
    next: HexagonSide[] = [],
    index = 0
  ): HexagonSide {
    const isLast = index === patern.length - 1
    const sides = isLast ? next : [drawPatern(patern, next, index + 1)]
    return { face: patern[index], sides }
  }

  function repeat(nb: number, patern: FaceIndex[]): HexagonSide {
    if (nb === 1) return drawPatern(patern)
    return drawPatern(patern, [repeat(nb - 1, patern)])
  }

  function drawItem(item: MenuItem): HexagonSide {
    return {
      ...item,
      face: 3,
      sides: [
        {
          face: 2,
          sides: [drawPatern([3, 2, 4])],
        },
        { face: 3 },
      ],
    }
  }

  function nextItem(items: MenuItem[]) {
    const [next, next2, ...rest] = items
    const drawNext: HexagonSide[] = []
    if (next) drawNext.push({ face: 3, sides: [drawItem(next)] })
    if (next2) {
      const drawRest = [drawItem(next2)]
      if (rest) drawRest.push(nextItem(rest))
      drawNext.push(
        drawPatern([5, 3], [{ face: 3 }, drawPatern([5, 3], drawRest)])
      )
    }

    // Add special ending to the patern
    if (!next && !next2) drawNext.push(drawPatern([5, 3, 2, 3, 2]))
    if (next && !next2) drawNext.push(drawPatern([5, 3, 5, 3, 2, 3, 3, 2]))

    return drawPatern([5, 3], drawNext)
  }

  const sides: HexagonSide[] = [
    { face: 3, sides: [repeat(2, [2, 3])] },
    {
      face: 4,
      sides: [drawItem({ label: 'Acceuil', href: '/' }), nextItem(items)],
    },
    { face: 0, permanent: true },
    { face: 1, permanent: true },
    { face: 2, permanent: true, sides: [{ face: 2, permanent: true }] },
    { face: 5, permanent: true },
  ]
</script>

<ClickOutside on:click_outside={() => (open = false)}>
  <Svg {size} class="fixed right-2 top-2 z-10">
    <Hexagon
      on:click={() => (open = !open)}
      {open}
      class="hover:fill-primary-light cursor-pointer"
      gap={150}
      {sides}
    >
      <MenuLines {open} />
    </Hexagon>
  </Svg>
</ClickOutside>

// site/src/lib/hexagon/Menu.tsx
import { createSignal } from 'solid-js'
import {
  Hexagon,
  viewWidth,
  viewHeight,
  HexagonProps,
  FaceIndex,
} from './Hexagon'

interface Button {
  label: string
  href: string
}

export interface Props {
  buttons: Button[]
  size?: number
}

export function Menu(props: Props) {
  const [open, setOpen] = createSignal(false)

  const defaultSize = 50

  function handleClick() {
    setOpen((v) => !v)
  }

  function draw(
    patern: FaceIndex[],
    next: HexagonProps[] = [],
    index = 0
  ): HexagonProps {
    const isLast = index === patern.length - 1
    const sides = isLast ? next : [draw(patern, next, index + 1)]
    return { face: patern[index], sides }
  }

  function repeat(nb: number, patern: FaceIndex[]): HexagonProps {
    if (nb === 1) return draw(patern)
    return draw(patern, [repeat(nb - 1, patern)])
  }

  function drawButton({ label, href }: Button): HexagonProps {
    return {
      label,
      href,
      face: 3,
      sides: [
        {
          face: 2,
          sides: [{ face: 3, hide: true, sides: [draw([2, 3, 5])] }],
        },
        { face: 3 },
      ],
    }
  }

  function nextButton(btns: Button[]) {
    if (!btns) return {}

    const [next, next2, ...rest] = btns

    const drawNext: HexagonProps[] = []
    if (next) drawNext.push({ face: 3, sides: [drawButton(next)] })
    if (next2) {
      const drawRest = [drawButton(next2)]
      if (rest) drawRest.push(nextButton(rest))
      drawNext.push(draw([5, 3], [{ face: 3 }, draw([5, 3], drawRest)]))
    }

    return draw([5, 3], drawNext)
  }

  return (
    <svg
      xmlns='http://www.w3.org/2000/svg'
      width={props.size || defaultSize}
      height={props.size || defaultSize}
      viewBox={`0 0 ${viewWidth} ${viewHeight}`}
      class='overflow-visible fill-primary stroke-primary-dark'
    >
      <Hexagon
        isMenuButton
        open={open()}
        visible
        class='hover:fill-primary-light'
        onClick={handleClick}
        gap={150}
        sides={[
          { face: 3, sides: [repeat(2, [2, 3])] },
          {
            face: 4,
            sides: [
              drawButton({ label: 'Acceuil', href: '/' }),
              nextButton(props.buttons),
            ],
          },
          { face: 0, visible: true },
          { face: 1, visible: true },
          { face: 2, visible: true },
          { face: 5, visible: true },
        ]}
      />
    </svg>
  )
}
